Add option to install specific kernel and boot it by default
storpool/ansible pull request #49
Opened 2022-02-25 13:08 UTC by imarkov-storpool

If this looks OK, I will also try to add `kexec` for faster reboots into the new kernel.

2022-02-25 13:19 UTC, netcho requested changes
It looks pretty much OK, I've left some minor comments.

2022-02-25 13:19 UTC, netcho commented on roles/2_setup-infra/tasks/subtasks/dependencies-debian.yml
> +  include_tasks: "kernel.yml"
Please use a more elaborate naming scheme, for example ``boot_into_updated_kernel`` or something similar.

2022-02-25 13:19 UTC, netcho commented on roles/2_setup-infra/tasks/subtasks/dependencies-redhat.yml
> +  include_tasks: "kernel.yml"
Please use a more elaborate naming scheme, for example, `boot_into_updated_kernel` or something similar.

2022-02-25 13:19 UTC, netcho commented on roles/2_setup-infra/tasks/subtasks/kernel.yml
> +- name: Get current kernel
It's better to make Ansible regather facts, the kernel command line might've changed.

2022-02-25 14:37 UTC, tanev commented on roles/2_setup-infra/files/set_default_kernel
> +function set_grub_default {
btw, I know it says #!/bin/bash on the first line, but it is a good idea to always use foo(){} anyway:
http://mywiki.wooledge.org/BashPitfalls#function_foo.28.29

2022-02-25 14:38 UTC, tanev commented on roles/2_setup-infra/files/set_default_kernel
> +    if [[ -z "${grub_cfg}" ]]; then
No need for the quotes inside the [[]]

2022-02-25 14:40 UTC, tanev commented on roles/2_setup-infra/files/set_default_kernel
> +new_default=$(parse_boot_loader_entries)
Add quotes here, please.

2022-03-08 10:53 UTC, netcho approved these changes

2022-03-08 10:54 UTC, merged